apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumption
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumption
  template:
    metadata:
      labels:
        app: consumption
    spec:
      containers:
      - name: consumption
        image: youthful_yonath/consumption:0.1
        ports:
        - containerPort: 8081 # 내부 컨테이너 포트
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: consumption
spec:
  selector:
    app: consumption
  ports:
  - protocol: TCP
    port: 3000 # 외부에 노출할 포트
    targetPort: 8081 # 컨테이너 내부 포트
  type: LoadBalancer