apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumptions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumptions
  template:
    metadata:
      labels:
        app: consumptions
    spec:
      containers:
      - name: consumptions
        image: choiyoorim/consumptions:0.1
        ports:
        - containerPort: 8081 # 내부 컨테이너 포트
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: consumptions
spec:
  selector:
    app: consumptions
  ports:
  - protocol: TCP
    port: 3000 # 외부에 노출할 포트
    targetPort: 8081 # 컨테이너 내부 포트
  type: LoadBalancer